# Generated by Django 2.0.4 on 2018-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_auto_20180618_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='brand_photo',
            field=models.CharField(default=5, max_length=1000),
            preserve_default=False,
        ),
    ]
